server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/customers
    username: amigoscode
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true