name: CD - Deploy Backend

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - backend/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: amigoscode
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: customer
        ports:
          - 5432:5432
          # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml' # optional
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${secrets.DOCKERHUB_USERNAME}
          password: ${secrets.DOCKERHUB_ACCESSTOKEN}
      - name: Set Build Number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
